name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker build . -t myimage
      - name: Run Dockerfile
        run: docker run myimage
      - uses: Mryan2005/GitBookBuildAction@main
        with:
          gitbook_version: '3.2.3'
          gitbook_input: './testboook'
          gitbook_output: '_book'
      - name: check gitbook_output
        run: ls ./output